server:
  port: 8081
  tomcat:
    max-http-header-size: 8192
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/medicalservice?useUnicode=true&characterEncoding=utf-8&allowmultiqueries=true&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    connection-test-query: SELECT 1 FROM DUAL
    connection-timeout: 600000
    maximum-pool-size: 500
    max-lifetime: 1800000
    minimum-idle: 20
    validation-timeout: 3000
    idle-timeout: 60000
    connection-init-sql: SET NAMES utf8mb4
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.medicalservice.domain

#showSql
logging:
  level:
    com:
      example:
       medicalservice:
          mapper : debug



